[package]
name = "ecmora-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ecmora-hir = { path = "../ecmora-hir" }
ecmora-ir = { path = "../ecmora-ir" }
ecmora-value = { path = "../ecmora-value" }

[dev-dependencies]
ecmora-frontend-oxc = { path = "../ecmora-frontend-oxc" }
